pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'composer install --no-interaction --prefer-dist --no-progress'
                sh 'npm ci'
            }
        }

        stage('Format Check') {
            steps {
                sh 'composer test:lint'
            }
        }
    }
}
